<testsuite name="Testem Tests" tests="2232" skipped="0" failures="2"
           timestamp="Thu Jan 23 2020 14:07:18 GMT-0800 (Pacific Standard Time)" time="40.535">
    <testcase classname="Chrome 79.0" name="LoggedInOrdersRoute exists " time="0.005">
        <error message="(0 , _chai.expect)(...).to.be is not a function"><![CDATA[Source:
TypeError: (0 , _chai.expect)(...).to.be is not a function
    at Context.<anonymous> (http://localhost:4203/starfox/assets/tests.js:12098:35)
    at invoke (http://localhost:4203/starfox/assets/test-support.js:13227:21)
    at Context.method (http://localhost:4203/starfox/assets/test-support.js:13292:13)
    at callFnAsync (http://localhost:4203/starfox/assets/test-support.js:4500:8)
    at Test.Runnable.run (http://localhost:4203/starfox/assets/test-support.js:4452:7)
    at Runner.runTest (http://localhost:4203/starfox/assets/test-support.js:4940:10)
    at http://localhost:4203/starfox/assets/test-support.js:5046:12
    at next (http://localhost:4203/starfox/assets/test-support.js:4860:14)
    at http://localhost:4203/starfox/assets/test-support.js:4870:7
    at next (http://localhost:4203/starfox/assets/test-support.js:4802:14)]]></error>
    </testcase>
    <testcase classname="Restaurants::Ranking::ranking restaurants by online ordering"
              name="test_0001_counts all closed orders in this month" time="4.358696000010241"
              assertions="12"></testcase>
</testsuite>
